# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_auto_20170924_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='cueuser',
            name='home_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cueuser',
            name='home_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
