# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0005_event_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
