# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0006_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 24, 10, 23, 9, 934595)),
            preserve_default=False,
        ),
    ]
