# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0007_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='iso_timezone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='bot_api.Place'),
        ),
    ]
