# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0009_auto_20170924_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
